"""Generate src/EmbeddedAssets.g.cs from the built model, texture and icon files.

Embedding the assets makes the plugin a single self-contained DLL, so distributing it
is just one file. The payload is Deflate-compressed before being base64'd, which cuts
the source (and therefore the DLL) to roughly a third. The loader still prefers a
loose file next to the DLL when one exists, so a custom model can be dropped in
without rebuilding.
"""
import base64
import os
import zlib

# Project root is the parent of tools/, so the script works from any drive or checkout.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "EmbeddedAssets.g.cs")

# logical name -> path. manifest.json is build bookkeeping, not a shipped asset, so it
# must never be swept into the resource table (that would change the embedded count).
ASSETS = [
    ("MiffyMesh", os.path.join(ROOT, "assets", "miffy.psmesh")),
    ("MiffyShading", os.path.join(ROOT, "assets", "miffy_shading.png")),
    ("MiffyIcon", os.path.join(ROOT, "assets", "icons", "icon_miffy.png")),
    ("ZichaoXiongMesh", os.path.join(ROOT, "assets", "zichaoxiong.psmesh")),
    ("ZichaoXiongShading", os.path.join(ROOT, "assets", "zichaoxiong_shading.png")),
    ("ZichaoXiongIcon", os.path.join(ROOT, "assets", "icons", "icon_zichaoxiong.png")),
]

CHUNK = 40000  # characters per string literal


def emit(fh, name, raw, packed):
    encoded = base64.b64encode(packed).decode("ascii")
    chunks = [encoded[i:i + CHUNK] for i in range(0, len(encoded), CHUNK)]
    ratio = 100.0 * len(packed) / max(1, len(raw))
    fh.write(f"        // {name}: {len(raw)} bytes raw -> {len(packed)} bytes deflate "
             f"({ratio:.0f}%)\n")
    fh.write(f"        private const string {name}Base64 =\n")
    for i, chunk in enumerate(chunks):
        suffix = ";" if i == len(chunks) - 1 else " +"
        fh.write(f'            "{chunk}"{suffix}\n')
    fh.write("\n")


def main():
    entries = []
    for name, path in ASSETS:
        # manifest.json is build bookkeeping (which 3MF produced which mesh), not a
        # shipped file. It lives in assets/ so it is explicitly excluded here: adding it
        # to the embedded table would change the resource count verify_embedded.py
        # expects and ship a file the runtime never reads.
        if os.path.basename(path) == "manifest.json":
            continue
        if not os.path.exists(path):
            raise SystemExit("missing asset: " + path)
        with open(path, "rb") as fh:
            raw = fh.read()
        # zlib.compress emits a zlib wrapper; strip it so C# DeflateStream can read it.
        packed = zlib.compress(raw, 9)[2:-4]
        entries.append((name, path, raw, packed))

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// <auto-generated>\n")
        fh.write("//     Generated by tools/embed_assets.py. Do not edit by hand.\n")
        fh.write("//     Regenerate after changing anything in assets/.\n")
        fh.write("// </auto-generated>\n")
        fh.write("using System;\n")
        fh.write("using System.Collections.Generic;\n")
        fh.write("using System.IO;\n")
        fh.write("using System.IO.Compression;\n\n")
        fh.write("namespace PlushieSwap\n{\n")
        fh.write("    /// <summary>\n")
        fh.write("    /// The model, shading and icon files, carried inside the DLL (deflate\n")
        fh.write("    /// compressed) so the mod ships as a single file. A loose file beside the\n")
        fh.write("    /// DLL still wins, which keeps custom models possible without rebuilding.\n")
        fh.write("    /// </summary>\n")
        fh.write("    internal static class EmbeddedAssets\n    {\n")
        for name, _, raw, packed in entries:
            emit(fh, name, raw, packed)
        fh.write("        private static readonly Dictionary<string, string> Table =\n")
        fh.write("            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)\n        {\n")
        for name, path, _, _ in entries:
            fh.write(f'            {{ "{os.path.basename(path)}", {name}Base64 }},\n')
        fh.write("        };\n\n")
        fh.write("        private static readonly Dictionary<string, byte[]> Cache =\n")
        fh.write("            new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);\n\n")
        fh.write("        /// <summary>True when the DLL carries this file.</summary>\n")
        fh.write("        internal static bool Has(string fileName)\n        {\n")
        fh.write("            return !string.IsNullOrEmpty(fileName) && Table.ContainsKey(fileName);\n")
        fh.write("        }\n\n")
        fh.write("        /// <summary>Returns the decompressed bytes for a file name, or null.</summary>\n")
        fh.write("        internal static byte[] Get(string fileName)\n        {\n")
        fh.write("            if (string.IsNullOrEmpty(fileName))\n            {\n                return null;\n            }\n\n")
        fh.write("            byte[] cached;\n")
        fh.write("            if (Cache.TryGetValue(fileName, out cached))\n            {\n                return cached;\n            }\n\n")
        fh.write("            string encoded;\n")
        fh.write("            if (!Table.TryGetValue(fileName, out encoded))\n            {\n                return null;\n            }\n\n")
        fh.write("            try\n            {\n")
        fh.write("                byte[] packed = Convert.FromBase64String(encoded);\n")
        fh.write("                byte[] raw = Inflate(packed);\n")
        fh.write("                Cache[fileName] = raw;\n")
        fh.write("                return raw;\n")
        fh.write("            }\n            catch (Exception ex)\n            {\n")
        fh.write("                DiagnosticLog.Error(\"Failed to unpack \" + fileName + \": \" + ex.Message);\n")
        fh.write("                return null;\n            }\n")
        fh.write("        }\n\n")
        fh.write("        private static byte[] Inflate(byte[] packed)\n        {\n")
        fh.write("            using (MemoryStream input = new MemoryStream(packed, false))\n")
        fh.write("            using (DeflateStream deflate = new DeflateStream(input, CompressionMode.Decompress))\n")
        fh.write("            using (MemoryStream output = new MemoryStream())\n            {\n")
        fh.write("                deflate.CopyTo(output);\n")
        fh.write("                return output.ToArray();\n")
        fh.write("            }\n")
        fh.write("        }\n")
        fh.write("    }\n}\n")

    raw_total = sum(len(r) for _, _, r, _ in entries)
    packed_total = sum(len(p) for _, _, _, p in entries)
    print(f"wrote {OUT}")
    print(f"  {len(entries)} assets: {raw_total/1024:.0f} KB raw -> "
          f"{packed_total/1024:.0f} KB deflate -> {os.path.getsize(OUT)/1024:.0f} KB source")


if __name__ == "__main__":
    main()
